apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-native-config
  namespace: cloud-native
data:
  APP_NAME: "Cloud Native Kubernetes Lab"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"