apiVersion: v1
kind: Secret

metadata:
  name: hello-app-secret
  namespace: production-lab

type: Opaque

stringData:
  DB_USERNAME: admin
  DB_PASSWORD: password123
  JWT_SECRET: my-super-secret-key