---
- name: Update packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install packages
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - vim
      - htop
      - jq
      - tree
    state: present