apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: hello-app-ingress
  namespace: production-lab

spec:
  tls:
    - hosts:
        - kubernetes.charithkalhara.me
      secretName: hello-app-tls

  rules:
    - host: kubernetes.charithkalhara.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 80