---
- name: Update repository
  git:
    repo: https://github.com/CharithKalhara/cloud-native-kubernetes--lab.git
    dest: /home/{{ ansible_user }}/cloud-native-kubernetes--lab
    version: main
    update: yes
    force: yes

- name: Create namespace
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/namespace/

- name: Apply ConfigMaps
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/configmap/

- name: Apply Secrets
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/secret/

# ADD THIS
- name: Apply RBAC
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/rbac/

- name: Apply Storage
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/storage/

- name: Apply Deployments
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/deployment/

- name: Apply Services
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/service/

- name: Apply HPA
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/hpa/

- name: Apply Ingress
  command: kubectl apply -f /home/{{ ansible_user }}/cloud-native-kubernetes--lab/kubernetes/ingress/

- name: Restart deployment
  command: kubectl rollout restart deployment hello-app -n production-lab

- name: Wait for rollout
  command: kubectl rollout status deployment hello-app -n production-lab --timeout=300s
  register: rollout
  ignore_errors: true

- name: Show Pods
  command: kubectl get pods -n production-lab -o wide
  register: pods

- debug:
    var: pods.stdout_lines

- name: Describe Deployment
  command: kubectl describe deployment hello-app -n production-lab
  register: deployment

- debug:
    var: deployment.stdout_lines

- name: Show Recent Events
  command: kubectl get events -n production-lab --sort-by=.metadata.creationTimestamp
  register: events

- debug:
    var: events.stdout_lines

- name: Show Services
  command: kubectl get svc -n production-lab

- name: Show Ingress
  command: kubectl get ingress -n production-lab

- name: Fail if rollout failed
  fail:
    msg: "Deployment rollout failed."
  when: rollout.rc != 0